### ISSUE TITLE
Godot objects declared in Kotlin are not properly initialized

### ISSUE THREAD

**Issue by CedNaru** [utopia-rise/godot-kotlin#231]
I'm currently trying to implement the benchmarks for the new bindings. But a lot of calls crash.

I noticed that the cause was when I am trying to use a Godot Object that has been created directly from Kotlin.

What is working:
-Using a CoreType coming from Godot
-Using a CoreType created in Kotlin
-Using an Object coming from Godot

What is not working:
-Using an Object created in Godot.

I tried several methods like:
![image](https://user-images.githubusercontent.com/31470327/89924601-8c4b1e80-dc02-11ea-8844-91ded963677f.png)
![image](https://user-images.githubusercontent.com/31470327/89924555-7ccbd580-dc02-11ea-9aff-3d3b00bb293d.png)
![image](https://user-images.githubusercontent.com/31470327/89924711-b56baf00-dc02-11ea-9da6-d99ba964bce5.png)

None of them works.
It ran the debugger many times and it seems that the issue is that the ptr is never properly initialized. 
When it's sent to Godot, I just get a segfault error:
![image](https://user-images.githubusercontent.com/31470327/89924985-0d0a1a80-dc03-11ea-8e70-455a3b188867.png)

**Comment by raniejade** [comment]
Fixed in #234.
