### ISSUE TITLE
Add choice for target between RELEASE and DEBUG

### ISSUE THREAD

**Issue by piiertho** [utopia-rise/godot-kotlin#28]
**Describe the problem or limitation you are having in your project:**

For now, release or debug is hardcoded in gradle build script, we should be able to specify a release target or to have one by default, that is the same for all projects (coroutines project is in RELEASE mode).

**Describe how this feature / enhancement will help you overcome this problem or limitation:**

User would be able to specify a release target.

**Show a mock up screenshots/video or a flow diagram explaining how your proposal will work:**

None to provide

**Describe implementation detail for your proposal (in code), if possible:**

1) Add a target parameter, which would be called with `-Ptarget=RELEASE/DEBUG`:
```kotlin
val target: String by project
```
2) Modify this block to conditionally select target:
```kotlin
this.target.binaries {
    sharedLib(listOf(org.jetbrains.kotlin.gradle.plugin.mpp.NativeBuildType.RELEASE))
}
```

**If this enhancement will not be used often, can it be worked around with a few lines of code?:**

It depends on build scripts.

**Is there a reason why this should be in this project and not individually solved?:**

We should be able to publish release

**Comment by Wavesonics** [comment]
Recommend closing this issue as PR #35 implemented this.

**Comment by chippmann** [comment]
> Recommend closing this issue as PR #35 implemented this.

True. Closing it.
