### ISSUE TITLE
Godot Gradle plugin config() should auto discover classes.json files

### ISSUE THREAD

**Issue by Wavesonics** [utopia-rise/godot-kotlin#34]
This would eliminate another maintenance step, and it would simplify the Godot Editor plugin I'm working on as it currently doesn't work out of the box because these need to be entered manually.

**Comment by chippmann** [comment]
If it is really urgent then we can implement it now, but if it is not, we shouldn't as #2 with the annotation processing will make the json files obsolete.

**Comment by Wavesonics** [comment]
Oh I must have been confused, there was a conversation that made me think we were running out of options on the annotation processor, and it might end up not working.

Also even if it did work I thought the annotation processor would just be producing these json files and we'd still need to point the build script at them somehow, how's it planned to work so that we don't need the json at all?

Well anyway that's all great news!

**Comment by chippmann** [comment]
Ah no we were running out of options but fresh ideas are coming in. We now have a solution that we will test for now.
It will directly generate the binding code. Json was doing the same. We were parsing the json and generate binding code with the information provided. Now we dont need that step anymore. We directly generate that code from the annotations.

**Comment by Wavesonics** [comment]
Damn that is cool, excited to see it!

**Comment by chippmann** [comment]
Closing this now in favor of #2 .
Feel free to reopen it if the solution does not hold up to your expectations.
