### ISSUE TITLE
Implement godot's platformer to test Kotlin's integration

### ISSUE THREAD

**Issue by piiertho** [utopia-rise/godot-kotlin#37]
**Describe the problem or limitation you are having in your project:**

We need to know which methods are missing (like it was the case with set on Dictionary).

**Describe how this feature / enhancement will help you overcome this problem or limitation:**

It will test kotlin integration on a bigger project than our sample. With this we should be able to see if some basic methods are missing.

**Show a mock up screenshots/video or a flow diagram explaining how your proposal will work:**

None to provide.

**Describe implementation detail for your proposal (in code), if possible:**

Rewrite GDQuest's platformer implementation in Kotlin.

**If this enhancement will not be used often, can it be worked around with a few lines of code?:**

Not appropriate.

**Is there a reason why this should be in this project and not individually solved?:**

Not appropriate. But it can be done in a seperate github, I guess this should be discussed.

**Comment by raniejade** [comment]
If you're planning to use composite builds you might be interested in this: https://github.com/JetBrains/kotlin-native/issues/3834 :)

And as a side note: https://github.com/JetBrains/kotlin-native/issues/3877

**Comment by chippmann** [comment]
@raniejade Thanks a lot for the info!
The usage of composite builds is definitely worth to discuss. But not yet used in any of the samples nor do i think it should be used for this one.
But regarding the release problem I think you saved us a lot of debugging. I really appreciate it!

**Comment by CedNaru** [comment]
Implementation on a break.
 The new casting system is required to finish it as I can't use custom object inside another script.

**Comment by chippmann** [comment]
@CedNaru I guess this can be closed as @raniejade implemented it now in the new binding impl?
