### ISSUE TITLE
Implement performance test

### ISSUE THREAD

**Issue by piiertho** [utopia-rise/godot-kotlin#38]
**Describe the problem or limitation you are having in your project:**

We currently don't know how Kotlin native wrapper performs.

**Describe how this feature / enhancement will help you overcome this problem or limitation:**

It will make us able to benchmark the wrapper.

**Show a mock up screenshots/video or a flow diagram explaining how your proposal will work:**

None to provide.

**Describe implementation detail for your proposal (in code), if possible:**

There are performance test addons for godot. Implementing one in kotlin would to the job.
Like this one: https://github.com/cart/godot3-bunnymark

**If this enhancement will not be used often, can it be worked around with a few lines of code?:**

Not appropriate.

**Is there a reason why this should be in this project and not individually solved?:**

Not appropriate.

**Comment by CedNaru** [comment]
I suggest this one: https://godotengine.org/asset-library/asset/510.
I know a C++ and C# versions already exist too.

**Comment by CedNaru** [comment]
Going to PR later BunnyMark and Game Of life benchmark.
Performances are awful but it works.
