### ISSUE TITLE
Implement the global functions of GDScript in the GD singleton

### ISSUE THREAD

**Issue by CedNaru** [utopia-rise/godot-kotlin#52]
**Describe the problem or limitation you are having in your project:**

When converting script from GDScript to Kotlin, there were a lot of functions I couldn't use out of the box.
Some are straightforward, some need to be locally rewritten, some need to be imported from external Kotlin package.

**Describe how this feature / enhancement will help you overcome this problem or limitation:**

The idea is to implement the different function of GdScript described here.
https://docs.godotengine.org/en/3.2/classes/class_@gdscript.html

Use cases:
- Math Functions
- Files Loading
- Random numbers generation
- Shortcuts to many Godot objects without the need to instantiate them.

**Describe implementation detail for your proposal (in code), if possible:**
These functions could be implementented in the GD singleton just like the Print function is today.

**Comment by chippmann** [comment]
I personally don't like the GD singleton and want to get rid of it wherever we can.
Personally I'm for global functions to implement your proposal.

**Comment by chippmann** [comment]
I'll implememt this together with #39

**Comment by chippmann** [comment]
@CedNaru I assigned you this (a little bit older) issue as you are working on it currently in the master merge.
Feel free to close it otherwise if you don't see it fit.

**Comment by CedNaru** [comment]
Okay:
A reminder that we decided to keep the gd singleton in order to have a safe namespace as the godot.core package is getting a bit too much bloated now.
