### ISSUE TITLE
Automatically add a dependency to the godot-library in the gradle plugin

### ISSUE THREAD

**Issue by raniejade** [utopia-rise/godot-kotlin#74]
The version used should be similar to the gradle plugin. This can be achieved by embedding the project.version in a properties file bundled together with the artifact jar.The plugin read the version during runtime.

**Comment by chippmann** [comment]
@raniejade Is this issue still necessary? We already implemented this in master-merge right?

**Comment by raniejade** [comment]
I can't remember 😅 - I'll have to check again.

**Comment by chippmann** [comment]
@raniejade still a thing or can i close it?

**Comment by raniejade** [comment]
This is done.
