### ISSUE TITLE
Add API code generation as gradle task

### ISSUE THREAD

**Issue by piiertho** [utopia-rise/godot-kotlin#86]
**Describe the problem or limitation you are having in your project:**

For the merge purpose, we decided to set api code generation as a gradle task.

**Describe how this feature / enhancement will help you overcome this problem or limitation:**

Not appropriate

**Show a mock up screenshots/video or a flow diagram explaining how your proposal will work:**

See @raniejade repository

**Describe implementation detail for your proposal (in code), if possible:**

Move code to `buildSrc` of project.
Add a task implementation.
Call task from `godot-library` gradle.

**If this enhancement will not be used often, can it be worked around with a few lines of code?:**

Not appropriate.

**Is there a reason why this should be in this project and not individually solved?:**

Not appropriate.

**Comment by chippmann** [comment]
@piiertho This issue can be closed right?

**Comment by piiertho** [comment]
This cannot be closed right now, we need to merge api generation branch first.
