### ISSUE TITLE
EntryGenerator DefaultValues (3): Support for Resources

### ISSUE THREAD

**Issue by chippmann** [utopia-rise/godot-kotlin#99]
Implement default value support for Resources and custom Resources.

The user would have to write the following:
```kotlin
@RegisterProperty
lateinit var resource: Resource //if not lateinit -> fail, customResources: just have to derive from Resource but are exported as Resource and not as custom type
```

**Implementation hints:**
- Files that need to be changed: `PropertyDefaultValueProvider` and `PropertyHintTypeMapper`
- Provide proper error messages (with Expcetions for now. MessageCollector will be implemented later)
- Default values need to be wrapped in a `Variant`
- A value type hint needs to be supplied at registration time
- Resource must be defined as lateinit and does NOT support default values! -> this must fail otherwise at compile time!
- A custom resource should be registered as just a resource and be casted back to the custom type when set by godot
- Registration should look like:  
```kotlin
property("nameOfProperty", TestingClass::propertyReference, STRING /*This is the püroperty type*/, Variant("defaultValue") /*This is the default value*/, true /**visible in editor/, DISABLED /*RPCMode*/, GODOT_PROPERTY_HINT_GLOBAL_DIR /*hint type*/, "" /*hint string*/)
```

**Comment by raniejade** [comment]
@chippmann this done right? Can we close it?

**Comment by chippmann** [comment]
Sure i'll close it
